# Generated by Django 4.0.4 on 2022-06-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_incomeclient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedehqon',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
