# Generated by Django 4.0.2 on 2022-09-22 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_expensedehqon_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclient',
            name='income_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.incomeclient'),
        ),
        migrations.AlterField(
            model_name='expensedehqon',
            name='dehqon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client'),
        ),
        migrations.AlterField(
            model_name='expensedehqon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.product'),
        ),
        migrations.AlterField(
            model_name='expensesotuvchi',
            name='income_sotuvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.incomesotuvchi'),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaysi client oldi+', to='app.client'),
        ),
        migrations.AlterField(
            model_name='incomedehqon',
            name='dehqon_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.expensedehqon'),
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.product'),
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='sotuvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client'),
        ),
        migrations.AlterField(
            model_name='kallahasb',
            name='mijoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client'),
        ),
        migrations.AlterField(
            model_name='teri',
            name='mijoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client'),
        ),
    ]
