# Generated by Django 4.0.2 on 2022-09-22 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_expenseclient_income_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klientlar'},
        ),
        migrations.AlterModelOptions(
            name='expenseclient',
            options={'verbose_name': 'Klient chiqimi', 'verbose_name_plural': 'Klientlar chiqimlari'},
        ),
        migrations.AlterModelOptions(
            name='expensedehqon',
            options={'verbose_name': 'Dehqonning xarajati', 'verbose_name_plural': 'Dehqonlarning xarajatlari'},
        ),
        migrations.AlterModelOptions(
            name='expensesotuvchi',
            options={'verbose_name': 'Sotuvchi chiqimi', 'verbose_name_plural': 'Sotuvchilar chiqimlari'},
        ),
        migrations.AlterModelOptions(
            name='incomeclient',
            options={'verbose_name': 'Klient kirimi', 'verbose_name_plural': 'Klientlarning kirimlari'},
        ),
        migrations.AlterModelOptions(
            name='incomedehqon',
            options={'verbose_name': 'Dehqon kirimi', 'verbose_name_plural': 'Dehqonlar kirimlari'},
        ),
        migrations.AlterModelOptions(
            name='incomesotuvchi',
            options={'verbose_name': 'Sotuvchi kirimi', 'verbose_name_plural': 'Sotuvchilar kirimlari'},
        ),
        migrations.AlterModelOptions(
            name='kallahasb',
            options={'verbose_name': 'Kalla hasb', 'verbose_name_plural': 'Kalla hasblar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='xarajat',
            options={'verbose_name': 'Xarajat', 'verbose_name_plural': 'Xarajatlar'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='F.I.O'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(blank=True, choices=[('dehqon', 'Dehqon'), ('client', 'Qushxona Klienti(Sotib oluvhi)'), ('sotuvchi', 'Bozordagi sotuvchi'), ('kallahasb', 'Kalla hasb oluvchi sotuvchi'), ('Teri', 'Teri oluvchi sotuvchi')], max_length=125, null=True, verbose_name='Vazifasi (Clientning roli)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status_bozor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Bozor uchun sotuvchi'),
        ),
        migrations.AlterField(
            model_name='expenseclient',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='expenseclient',
            name='income_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.incomeclient', verbose_name='Klient chiqimi'),
        ),
        migrations.AlterField(
            model_name='expensedehqon',
            name='dehqon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='Dehqon'),
        ),
        migrations.AlterField(
            model_name='expensedehqon',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='expensedehqon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='expensedehqon',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='expensedehqon',
            name='status',
            field=models.CharField(blank=True, choices=[('progress', 'Jarayonda'), ('completed', 'Yakunlandi')], default='progress', max_length=125, null=True, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='expensedehqon',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name="Og'irligi"),
        ),
        migrations.AlterField(
            model_name='expensesotuvchi',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='expensesotuvchi',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='expensesotuvchi',
            name='income_sotuvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.incomesotuvchi', verbose_name='Sotuvchi chiqimi'),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaysi client oldi+', to='app.client', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='product_dehqon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qaysi dehqonni qoyi+', to='app.expensedehqon', verbose_name='Dehqonning mahsuloti'),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='status',
            field=models.CharField(blank=True, choices=[('bron', 'Bron qilindi'), ('progress', 'Jarayonda'), ('completed', 'Yakunlandi')], default='progress', max_length=125, null=True, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name="Og'irligi"),
        ),
        migrations.AlterField(
            model_name='incomedehqon',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='incomedehqon',
            name='dehqon_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.expensedehqon', verbose_name='Dehqon mahsuloti'),
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='sotuvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='Sotuvchi'),
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='status',
            field=models.CharField(blank=True, choices=[('progress', 'Jarayonda'), ('completed', 'yakunlandi')], default='progress', max_length=88, null=True, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name="Og'irligi"),
        ),
        migrations.AlterField(
            model_name='kallahasb',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='kallahasb',
            name='mijoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='kallahasb',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='kallahasb',
            name='soni',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='teri',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='teri',
            name='mijoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='teri',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='teri',
            name='soni',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='choise',
            field=models.CharField(blank=True, choices=[('qushxona', 'Qushxona uchun xarajat'), ('bozor', 'bozordagi xarajatlar')], max_length=125, null=True, verbose_name='Xarajat turi'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='comment',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sana'),
        ),
    ]
