# Generated by Django 4.0.2 on 2022-11-23 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_expenseclient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomebazarother',
            options={'ordering': ['-created_date'], 'verbose_name': 'Bozordan ichki mahsulotlar', 'verbose_name_plural': 'Bozor ichki mahsulotlari'},
        ),
        migrations.AddField(
            model_name='incomebazarother',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='Mijoz'),
        ),
    ]
