# Generated by Django 3.2.16 on 2022-11-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_incomebazarother_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazarAllIncomeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Soni')),
                ('weight', models.FloatField(blank=True, default=0, null=True, verbose_name="Og'irligi")),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('remote_id', models.IntegerField(verbose_name='Remote id')),
                ('source', models.CharField(choices=[('bozor', 'Bozor'), ('qushxona', 'Qushxona')], max_length=125, verbose_name='Manba')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Bozorga barcha sotib olingan mahsulotlar',
                'verbose_name_plural': 'Bozorga barcha sotib olingan mahsulotlar',
            },
        ),
    ]
