# Generated by Django 3.2.16 on 2022-11-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_bazarallincomestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazarallincomestock',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.client'),
            preserve_default=False,
        ),
    ]
