# Generated by Django 3.2.16 on 2022-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_bazarallincomestock_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazarallincomestock',
            name='price',
            field=models.IntegerField(default=70000, verbose_name='Narxi 1kg uchun'),
            preserve_default=False,
        ),
    ]
