# Generated by Django 4.0.2 on 2022-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_bazarallincomestock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesotuvchi',
            name='source',
            field=models.CharField(choices=[('bozor', 'Bozor'), ('qushxona', 'Qushxona')], default='qushxona', max_length=125, verbose_name='Manba'),
        ),
    ]
