# Generated by Django 4.0.2 on 2022-11-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_incomesotuvchi_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesotuvchi',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Miqdori'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='source',
            field=models.CharField(choices=[('bozor', 'Bozor'), ('qushxona', 'Qushxona')], default='qushxona', max_length=125, verbose_name='Manba'),
        ),
    ]
