# Generated by Django 4.1.3 on 2022-12-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_incomeclient_product_dehqon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesotuvchi',
            name='income_sotuvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tulovlar', to='app.incomesotuvchi', verbose_name='Sotuvchi chiqimi'),
        ),
        migrations.AlterField(
            model_name='incomesotuvchi',
            name='source',
            field=models.CharField(choices=[('bozor', 'Bozor'), ('qushxona', 'Qushxona')], default='qushxona', max_length=125, verbose_name='Manba'),
        ),
    ]
